# .github/workflows/build.yml
name: Build Application

on: # Optional, defined in the main file
  workflow_call: # Allows this job to be referenced
    inputs: {}
    secrets: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build
