name: Deploy

on:
  workflow_run:
    workflows: ["Dockerize"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH for EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-test-node-app:latest
          docker stop my-test-node-app || true
          docker rm my-test-node-app || true
          docker rmi $(docker images -f "dangling=true" -q) || true
          docker run -d --name my-test-node-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-test-node-app:latest
          docker system prune -af || true
          EOF

      - name: Cleanup local SSH key
        run: rm ec2_key.pem
