# .github/workflows/deploy.yml
name: Deploy to EC2

on: # Optional, defined in the main file
  workflow_call:
    inputs: {}
    secrets:
      EC2_KEY:
        required: true
      EC2_USER:
        required: true
      EC2_PUBLIC_IP:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH for EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-todo-app:latest
          docker stop my-todo-app || true
          docker rm my-todo-app || true
          docker rmi $(docker images -f "dangling=true" -q) || true
          docker run -d --name my-todo-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-todo-app:latest
          docker system prune -af || true
          EOF

      - name: Cleanup local SSH key
        run: rm ec2_key.pem
