# .github/workflows/dockerize.yml
name: Dockerize Application

on: # Optional, defined in the main file
  workflow_call:
    inputs: {}
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t bestPracticeApp .
          docker tag bestPracticeApp:latest ${{ secrets.DOCKER_USERNAME }}/bestPracticeApp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bestPracticeApp:latest

      - name: Log out from Docker Hub
        run: docker logout
