name: Dockerize

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t my-test-node-app .
          docker tag my-test-node-app:latest ${{ secrets.DOCKER_USERNAME }}/my-test-node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-test-node-app:latest

      - name: Log out from Docker Hub
        run: docker logout
