name: Create release
on:
    push:
      tags:
        - '*'  # Trigger the workflow for all tag pushes
jobs:
    build:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          # Checks out the code in the tag that triggered the workflow.
    
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.VERSION_TOKEN }}
          with:
            tag_name: ${{ github.ref }}  # This is the reference to the tag
            release_name: Release ${{ github.ref }}  # The release name, can use the tag name here
            body: |
              This is an automated release based on tag ${{ github.ref }}
            draft: false
            prerelease: false
  