name: Release

on:
  workflow_run:
    workflows: ["Build", "Versioning"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.${{ github.run_number }}
          release_name: "Release v1.${{ github.run_number }}"
          body: |
            Automated release created by GitHub Actions.
          draft: false
          prerelease: false
