name: Release

on:
  workflow_run:
    workflows: ["Build", "Versioning"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.${{ github.run_number }}
          body: |
            ## Release Notes
            This release was automatically created by GitHub Actions.
            - **Tag:** v1.${{ github.run_number }}
            - **Description:** Add your custom details here.
          draft: false
          prerelease: false
        env:
          GH_TOKEN: ${{ secrets.VERSION_TOKEN }}  # Ensure this is your GitHub token secret name
